version: 2.1
jobs:
  build:
    docker:
      - image: perldocker/perl-tester:5.32
    steps:
      - checkout
      - run:
          name: Example command
          command: perl -E 'say "Hello, World\n"'
