version: 2.1
jobs:
  build:
    docker:
      - image: perldocker/perl-tester:5.32
    steps:
      - checkout
      - run:
          name: Example command
          command: |
            perl \<<END
                use feature 'say';
                say "Look an entire Perl script";
                say "Right in the middle of my YAML";
                say "Whooo hooo";
            END
